ALTER TABLE "trainers"
  ADD COLUMN IF NOT EXISTS "clientsCount"        INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "certificationsCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "languages"           TEXT[]  NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "achievements"        TEXT[]  NOT NULL DEFAULT '{}';

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "birthDate"   TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "gender"      TEXT,
  ADD COLUMN IF NOT EXISTS "avatarColor" TEXT,
  ADD COLUMN IF NOT EXISTS "coverStyle"  TEXT,
  ADD COLUMN IF NOT EXISTS "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;