ALTER TABLE "exercises"
ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "duration" INTEGER NOT NULL DEFAULT 45,
    ADD COLUMN IF NOT EXISTS "restAfter" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "programs"
ADD COLUMN IF NOT EXISTS "videoId" TEXT;